---
title: "Process Control Charts"
date: "2022-10-03"
categories: [Process Control, R, ggplot2, engineering, manufacturing, tidyverse, code]
---

## Process Control Charts

If you do any work in engineering, manufacturing, processing, etc. you're likely
  to encounter Statistical Process Control. It is fundamental for understanding
  processes and makes up a good portion of the Six Sigma program. A very handy
  part of this system is the SPC Charts like X-Bar and S, x-Bar and R, MR, etc. 
  
There exists specialized software for making these graphs, but why bother when 
  you have R? 


This post is just going to be making simple versions with no special libraries, 
  but if you desire there are specialized R libraries for making these charts: 

- [qcc](https://cran.r-project.org/web/packages/qcc/index.html)
- [qicharts2](https://cran.r-project.org/web/packages/qicharts2/vignettes/qicharts2.html)
- [ggQC](https://cran.r-project.org/web/packages/ggQC/index.html)
- [And many more...](https://www.google.com/search?q=process+control&domains=r-project.org&sitesearch=r-project.org)


There are 3 main types of SPC Charts:

- X-Bar and S (Std. Dev, >10 samples per run/group)
- X-Bar and R (run range, <= 10 per run/group)
- X-Bar and M (change from run to run, when there is only 1 measure per group)

For a detailed explanation of 

[NIST Handbook](https://www.itl.nist.gov/div898/handbook/index.htm)

[Table of Constants](http://www.bessegato.com.br/UFJF/resources/table_of_control_chart_constants_old.pdf)

[45. LITHOGRA.DAT - lithography process (process control)](https://www.itl.nist.gov/div898/handbook/datasets/LITHOGRA.DAT)

[57. MONITOR-6_3_3_1.DAT - defects in wafers (counts based control charts)](https://www.itl.nist.gov/div898/handbook/datasets/MONITOR-6_3_3_1.DAT)

[68. NEGIZ4.DAT - lithography process (process control)](https://www.itl.nist.gov/div898/handbook/datasets/NEGIZ4.DAT)


```{r}
#| label: lithograph-data
#| child: "lithograph_control_charts.qmd"
```

