project:
  type: website
  output-dir: docs

website:
  title: "Tyler Clark"
  navbar:
    right:
      - blog.qmd
      - text: Archive
        href: archive.qmd
      - icon: github
        href: https://github.com/tclark89/
      - icon: linkedin
        href: https://www.linkedin.com/in/tyler-clark-5b5b511b5
format:
  html:
    theme: lumen
    css: styles.css



